import html2pdf from "html2pdf.js";

interface ExportOptions {
  filename?: string;
  margin?: number;
  imageQuality?: number;
}

export const exportToPDF = async (element: HTMLElement, options?: ExportOptions) => {
  const opt = {
    margin: options?.margin || 0.5,
    filename: options?.filename || "document.pdf",
    image: {
      type: "jpeg" as const, // ✅ Fix: use 'as const' for literal type
      quality: options?.imageQuality || 0.98,
    },
    html2canvas: {
      scale: 2,
      letterRendering: true,
      useCORS: true,
    },
    jsPDF: {
      unit: "in" as const, // ✅ Fix: use 'as const'
      format: "a4" as const, // ✅ Fix: use 'as const'
      orientation: "portrait" as const, // ✅ Fix: use 'as const'
    },
  };

  try {
    await html2pdf().set(opt).from(element).save();
    return true;
  } catch (error) {
    console.error("PDF export failed:", error);
    return false;
  }
};

export const exportContentToPDF = async (content: string, title: string) => {
  // Create a temporary container for PDF content
  const container = document.createElement("div");
  container.style.padding = "40px";
  container.style.backgroundColor = "white";
  container.style.fontFamily = "Arial, sans-serif";
  container.style.fontSize = "12pt";
  container.style.lineHeight = "1.5";
  container.style.color = "#333";

  // Add title
  const titleElement = document.createElement("h1");
  titleElement.textContent = title;
  titleElement.style.color = "#2563EB";
  titleElement.style.borderBottom = "2px solid #2563EB";
  titleElement.style.paddingBottom = "10px";
  titleElement.style.marginBottom = "20px";
  container.appendChild(titleElement);

  // Add content
  const contentDiv = document.createElement("div");
  contentDiv.innerHTML = content;
  container.appendChild(contentDiv);

  // Add footer
  const footer = document.createElement("div");
  footer.style.marginTop = "40px";
  footer.style.paddingTop = "20px";
  footer.style.borderTop = "1px solid #ddd";
  footer.style.textAlign = "center";
  footer.style.fontSize = "10pt";
  footer.style.color = "#999";
  footer.innerHTML = `Generated by DocuCollab · ${new Date().toLocaleDateString()}`;
  container.appendChild(footer);

  document.body.appendChild(container);
  const result = await exportToPDF(container, { filename: `${title}.pdf` });
  document.body.removeChild(container);

  return result;
};
